Gridview
gdt050579/GView pull request #150
Opened 2023-03-28 20:24 UTC by smocgeorgemarian

Changed constructor in order to respect macos compatibility

2023-05-25 19:00 UTC, gheorghitamutu requested changes

2023-05-25 19:00 UTC, gheorghitamutu commented on GViewCore/src/View/GridViewer/FindDialog.cpp
> +    const uint32 deltaHeight = DIALOG_HEIGHT_BINARY_FORMAT - DIALOG_HEIGHT_TEXT_FORMAT;
are sens sa le calculezi daca e posibil sa return early si sa nu le folosesti la nimic?

2023-05-27 22:14 UTC, smocgeorgemarian commented on GViewCore/src/View/GridViewer/FindDialog.cpp
> +    const uint32 deltaHeight = DIALOG_HEIGHT_BINARY_FORMAT - DIALOG_HEIGHT_TEXT_FORMAT;
Nope, modificat

2023-05-27 22:16 UTC, smocgeorgemarian commented on GViewCore/src/View/GridViewer/Instance.cpp
> +    grid->SetFilterOnCurrentColumn(filterValue);
Checkul legat de daca filtrul e gol e la nivel de processInput(), iar mai departe check-ul legat de rezultate/neselectare coloane pt filtru e la nivel de AppCUI. Ar trebui regandit sau puse check-uri suplimentare legate de alte cazuri?

2023-05-29 16:10 UTC, gheorghitamutu requested changes

2023-05-29 16:10 UTC, gheorghitamutu commented on GViewCore/src/View/GridViewer/Instance.cpp
> +    grid->SetFilterOnCurrentColumn(filterValue);
ma refeream daca `SetFilterOnCurrentColumn` sau `Filter` au valori de return ce ar trebui verificate

2023-06-04 08:18 UTC, smocgeorgemarian commented on GViewCore/src/View/GridViewer/Instance.cpp
> +    grid->SetFilterOnCurrentColumn(filterValue);
Am verificat acum, nu au

2023-06-05 12:49 UTC, gheorghitamutu approved these changes

2023-06-05 12:49 UTC, merged