[wip] Java
gdt050579/GView pull request #41
Opened 2022-04-11 09:14 UTC by xTachyon

2022-06-13 08:07 UTC, gdt050579 requested changes
Schimba pls din JAR in altceva ? (class ?!?)

2022-06-13 08:07 UTC, gdt050579 commented on CMakeLists.txt
> +add_subdirectory(Types/JAR)
Nu prea este JAR --> JAR e mai degraba o arhiva ZIP.  Poate .class ?

2024-01-03 17:37 UTC, gheorghitamutu commented on CMakeLists.txt
> +add_subdirectory(Types/JAR)
JCLASS

2024-03-03 13:10 UTC, gdt050579 approved these changes
Ok

2024-03-03 13:13 UTC, gheorghitamutu approved these changes

2024-03-08 15:30 UTC, merged